services:
  - type: web
    name: bahr-el-ghazal-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard (add ?sslmode=require)
      - key: ALLOWED_ORIGINS
        value: https://finance.bahrelghazalclinic.com
    healthCheckPath: /api/health